#!/usr/bin/env node
/**
 * Regenerate the API types from the backend's OpenAPI document.
 *
 *   node scripts/generate.mjs                          # fetch from localhost:8000
 *   node scripts/generate.mjs --url http://api:8000    # fetch from elsewhere
 *   node scripts/generate.mjs --from ./openapi.json    # use a checked-in snapshot
 *   node scripts/generate.mjs --check                  # CI: fail if output is stale
 *
 * `--check` is the important one. Run it in CI against a live backend and it
 * fails when the committed types no longer match the API — the frontend
 * equivalent of `alembic check`.
 */

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = dirname(dirname(fileURLToPath(import.meta.url)));
const argv = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = argv.indexOf(`--${name}`);
  return i === -1 ? fallback : argv[i + 1];
};
const CHECK = argv.includes("--check");
const URL_ = flag("url", "http://localhost:8000");
const FROM = flag("from", null);

/* ── 1. Obtain the spec ──────────────────────────────────────────────────── */

async function loadSpec() {
  if (FROM) return JSON.parse(readFileSync(FROM, "utf8"));
  const res = await fetch(`${URL_}/openapi.json`);
  if (!res.ok) {
    throw new Error(
      `GET ${URL_}/openapi.json -> ${res.status}. Start the backend ` +
        `(docker compose up api) or pass --from ./openapi.json.`,
    );
  }
  return res.json();
}

/* ── 2. Ergonomic alias layer over the raw generated schema ──────────────── */

const NOISE = new Set(["HTTPValidationError", "ValidationError"]);

function multipartAlias(name) {
  const core = name.slice("Body_".length).replace(/_(get|post|put|patch|delete)$/, "");
  return (
    core
      .split("_")
      .filter(Boolean)
      .slice(0, 3)
      .map((w) => w[0].toUpperCase() + w.slice(1))
      .join("") + "Body"
  );
}

function buildModels(spec) {
  const names = Object.keys(spec.components?.schemas ?? {}).sort();
  const bodies = names.filter((n) => n.startsWith("Body_"));
  const main = names.filter((n) => !n.startsWith("Body_") && !NOISE.has(n));

  const out = [
    "/**",
    " * Shared API types for the Civic platform — consumed by both `admin/` (Next.js)",
    " * and `mobile/` (Expo / React Native).",
    " *",
    " * GENERATED SURFACE. `schema.d.ts` is produced by `openapi-typescript` from the",
    " * backend's own OpenAPI document; this file is the ergonomic layer over it. Both",
    " * are regenerated by `npm run generate` — do not hand-edit either.",
    " *",
    " * The backend is the single source of truth. If a type here looks wrong, fix the",
    " * Pydantic model in `civic-backend/app/schemas/` and regenerate.",
    " */",
    "",
    'import type { paths, components, operations } from "./schema";',
    "",
    "export type { paths, components, operations };",
    "",
    "/** Every schema the API defines, keyed by name. */",
    'export type Schemas = components["schemas"];',
    "",
    "/* ── Model aliases ──────────────────────────────────────────────────────── */",
    "",
    ...main.map((s) => `export type ${s} = Schemas["${s}"];`),
    "",
    "/* ── Multipart request bodies ───────────────────────────────────────────── */",
    "/* FastAPI names these after the handler; these are readable aliases.        */",
    "",
  ];

  const seen = new Set();
  for (const s of bodies) {
    let alias = multipartAlias(s);
    let n = 2;
    while (seen.has(alias)) alias = `${multipartAlias(s).slice(0, -4)}${n++}Body`;
    seen.add(alias);
    out.push(`export type ${alias} = Schemas["${s}"];`);
  }

  out.push(
    "",
    "/* ── Error shapes ───────────────────────────────────────────────────────── */",
    "",
    "/** FastAPI 422 body — one entry per failed field. */",
    'export type HTTPValidationError = Schemas["HTTPValidationError"];',
    'export type ValidationError = Schemas["ValidationError"];',
    "",
    "/** What this API returns for 4xx/5xx that are not 422. */",
    "export interface ApiErrorBody {",
    "  detail: string;",
    "}",
    "",
    "/** Either error shape, which is what an interceptor actually has to handle. */",
    "export type ApiError = ApiErrorBody | HTTPValidationError;",
    "",
  );
  return out.join("\n");
}

/* ── 3. Write, or diff in --check mode ───────────────────────────────────── */

const written = [];
function emit(relPath, contents) {
  const abs = join(PKG, relPath);
  if (CHECK) {
    let current = "";
    try {
      current = readFileSync(abs, "utf8");
    } catch {
      /* missing counts as stale */
    }
    if (current !== contents) {
      console.error(`✗ stale: ${relPath}`);
      process.exitCode = 1;
    } else {
      console.log(`✓ ${relPath}`);
    }
    return;
  }
  writeFileSync(abs, contents);
  written.push(relPath);
}

const spec = await loadSpec();
const specJson = JSON.stringify(spec);
emit("openapi.json", JSON.stringify(sortDeep(spec), null, 2) + "\n");

const tmp = mkdtempSync(join(tmpdir(), "civic-types-"));
try {
  const specPath = join(tmp, "openapi.json");
  writeFileSync(specPath, specJson);
  const schema = execFileSync(
    "npx",
    ["--yes", "openapi-typescript@7.13.0", specPath],
    { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  );
  emit("src/schema.d.ts", schema);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}

emit("src/models.d.ts", buildModels(spec));

if (CHECK) {
  console.log(
    process.exitCode
      ? "\nTypes are out of date. Run `npm run generate` and commit the result."
      : "\nTypes match the live API.",
  );
} else {
  console.log(`Regenerated:\n${written.map((f) => `  ${f}`).join("\n")}`);
  console.log(
    "\nNote: src/endpoint-access.js is derived from the backend SOURCE (role\n" +
      "dependencies are not expressed in OpenAPI). Refresh it with:\n" +
      // ../../civic-backend resolves inside civic-frontend/, which is not where
      // the backend lives — the hint sent you to a path that does not exist.
      "  python3 scripts/derive-endpoint-access.py ../../../civic-backend",
  );
}

/** Stable key order so the committed snapshot diffs cleanly. */
function sortDeep(value) {
  if (Array.isArray(value)) return value.map(sortDeep);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((k) => [k, sortDeep(value[k])]),
    );
  }
  return value;
}
