/**
 * Shared API types for the Civic platform — consumed by both `admin/` (Next.js)
 * and `mobile/` (Expo / React Native).
 *
 * GENERATED SURFACE. `schema.d.ts` is produced by `openapi-typescript` from the
 * backend's own OpenAPI document; this file is the ergonomic layer over it. Both
 * are regenerated by `npm run generate` — do not hand-edit either.
 *
 * The backend is the single source of truth. If a type here looks wrong, fix the
 * Pydantic model in `civic-backend/app/schemas/` and regenerate.
 */

import type { paths, components, operations } from "./schema";

export type { paths, components, operations };

/** Every schema the API defines, keyed by name. */
export type Schemas = components["schemas"];

/* ── Model aliases ──────────────────────────────────────────────────────── */

export type AadharSendOTPRequest = Schemas["AadharSendOTPRequest"];
export type AadharSendOTPResponse = Schemas["AadharSendOTPResponse"];
export type AadharVerifyRequest = Schemas["AadharVerifyRequest"];
export type AdminSetupRequest = Schemas["AdminSetupRequest"];
export type AssignWorker = Schemas["AssignWorker"];
export type AuthProvidersResponse = Schemas["AuthProvidersResponse"];
export type AvailabilityUpdate = Schemas["AvailabilityUpdate"];
export type BadgeDefinitionOut = Schemas["BadgeDefinitionOut"];
export type BadgeOut = Schemas["BadgeOut"];
export type BookmarkResponse = Schemas["BookmarkResponse"];
export type BulkIssueRequest = Schemas["BulkIssueRequest"];
export type ChangePasswordRequest = Schemas["ChangePasswordRequest"];
export type ChangePhoneSendOTPRequest = Schemas["ChangePhoneSendOTPRequest"];
export type ChangePhoneVerifyRequest = Schemas["ChangePhoneVerifyRequest"];
export type ChatRequest = Schemas["ChatRequest"];
export type ChatResponse = Schemas["ChatResponse"];
export type ComplaintCreate = Schemas["ComplaintCreate"];
export type ComplaintResolve = Schemas["ComplaintResolve"];
export type ComplaintResponse = Schemas["ComplaintResponse"];
export type CreateAnnouncementRequest = Schemas["CreateAnnouncementRequest"];
export type CreateGeofenceRequest = Schemas["CreateGeofenceRequest"];
export type CreateSubAdminRequest = Schemas["CreateSubAdminRequest"];
export type CreateWorker = Schemas["CreateWorker"];
export type CustomIssueTypeResponse = Schemas["CustomIssueTypeResponse"];
export type DashboardStats = Schemas["DashboardStats"];
export type DepartmentEnum = Schemas["DepartmentEnum"];
export type DisputeCreate = Schemas["DisputeCreate"];
export type DisputeResolve = Schemas["DisputeResolve"];
export type DisputeResponse = Schemas["DisputeResponse"];
export type FlagRequest = Schemas["FlagRequest"];
export type ForgotPasswordRequest = Schemas["ForgotPasswordRequest"];
export type GeofenceListResponse = Schemas["GeofenceListResponse"];
export type GeofenceResponse = Schemas["GeofenceResponse"];
export type GoogleLoginRequest = Schemas["GoogleLoginRequest"];
export type GrantOverrideRequest = Schemas["GrantOverrideRequest"];
export type IssueCommentAuthor = Schemas["IssueCommentAuthor"];
export type IssueCommentCreate = Schemas["IssueCommentCreate"];
export type IssueCommentResponse = Schemas["IssueCommentResponse"];
export type IssueCreate = Schemas["IssueCreate"];
export type IssueListResponse = Schemas["IssueListResponse"];
export type IssuePriorityEnum = Schemas["IssuePriorityEnum"];
export type IssueReporterInfo = Schemas["IssueReporterInfo"];
export type IssueResponse = Schemas["IssueResponse"];
export type IssueSeverityEnum = Schemas["IssueSeverityEnum"];
export type IssueStatusEnum = Schemas["IssueStatusEnum"];
export type IssueTypeEnum = Schemas["IssueTypeEnum"];
export type IssueUpdate = Schemas["IssueUpdate"];
export type LeaderboardEntry = Schemas["LeaderboardEntry"];
export type LocationUpdate = Schemas["LocationUpdate"];
export type NotificationResponse = Schemas["NotificationResponse"];
export type PasswordLoginRequest = Schemas["PasswordLoginRequest"];
export type PublicIssueMarker = Schemas["PublicIssueMarker"];
export type RefreshTokenRequest = Schemas["RefreshTokenRequest"];
export type RegisterRequest = Schemas["RegisterRequest"];
export type ResetPasswordRequest = Schemas["ResetPasswordRequest"];
export type RewardTransactionOut = Schemas["RewardTransactionOut"];
export type SendMessageRequest = Schemas["SendMessageRequest"];
export type SendOTPRequest = Schemas["SendOTPRequest"];
export type SendOTPResponse = Schemas["SendOTPResponse"];
export type SetupStatusResponse = Schemas["SetupStatusResponse"];
export type ShiftUpsert = Schemas["ShiftUpsert"];
export type SubscribeRequest = Schemas["SubscribeRequest"];
export type SurveyCreate = Schemas["SurveyCreate"];
export type SurveyResponse = Schemas["SurveyResponse"];
export type SyncAction = Schemas["SyncAction"];
export type SyncRequest = Schemas["SyncRequest"];
export type SyncResponse = Schemas["SyncResponse"];
export type SyncResult = Schemas["SyncResult"];
export type TaskAcceptReject = Schemas["TaskAcceptReject"];
export type TokenResponse = Schemas["TokenResponse"];
export type UpdateGeofenceRequest = Schemas["UpdateGeofenceRequest"];
export type UpdateProfileRequest = Schemas["UpdateProfileRequest"];
export type UpdateSubAdmin = Schemas["UpdateSubAdmin"];
export type UpdateWorker = Schemas["UpdateWorker"];
export type UserResponse = Schemas["UserResponse"];
export type UserRewardSummary = Schemas["UserRewardSummary"];
export type VerifyOTPRequest = Schemas["VerifyOTPRequest"];
export type WorkerInvitationResult = Schemas["WorkerInvitationResult"];
export type WorkerStats = Schemas["WorkerStats"];
export type WorkerStatusUpdate = Schemas["WorkerStatusUpdate"];

/* ── Multipart request bodies ───────────────────────────────────────────── */
/* FastAPI names these after the handler; these are readable aliases.        */

export type ResolveTaskWorkersBody = Schemas["Body_resolve_task_workers_tasks__issue_id__resolve_post"];
export type TranscribeAudioIssuesBody = Schemas["Body_transcribe_audio_issues_transcribe_post"];
export type UploadComplaintPhotosBody = Schemas["Body_upload_complaint_photos_workers_complaints__complaint_id__photos_post"];
export type UploadDisputePhotosBody = Schemas["Body_upload_dispute_photos_issues__issue_id__dispute_photos_post"];
export type UploadPhotosIssuesBody = Schemas["Body_upload_photos_issues__issue_id__photos_post"];
export type UploadProfilePhotoBody = Schemas["Body_upload_profile_photo_auth_profile_photo_post"];

/* ── Error shapes ───────────────────────────────────────────────────────── */

/** FastAPI 422 body — one entry per failed field. */
export type HTTPValidationError = Schemas["HTTPValidationError"];
export type ValidationError = Schemas["ValidationError"];

/** What this API returns for 4xx/5xx that are not 422. */
export interface ApiErrorBody {
  detail: string;
}

/** Either error shape, which is what an interceptor actually has to handle. */
export type ApiError = ApiErrorBody | HTTPValidationError;
